from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start{CMD_INDEX}'
        self.MirrorCommand = f'pea{CMD_INDEX}'
        self.UnzipMirrorCommand = f'peaunzip{CMD_INDEX}'
        self.ZipMirrorCommand = f'peazip{CMD_INDEX}'
        self.CancelMirror = f'peacancel{CMD_INDEX}'
        self.CancelAllCommand = f'peacancelall{CMD_INDEX}'
        self.ListCommand = f'list{CMD_INDEX}'
        self.SearchCommand = f'search{CMD_INDEX}'
        self.StatusCommand = f'peastatus{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'peausers{CMD_INDEX}'
        self.AuthorizeCommand = f'peaauthorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'peaunauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'peaaddsudo{CMD_INDEX}'
        self.RmSudoCommand = f'pearmsudo{CMD_INDEX}'
        self.PingCommand = f'peaping{CMD_INDEX}'
        self.RestartCommand = f'pearestart{CMD_INDEX}'
        self.StatsCommand = f'peastats{CMD_INDEX}'
        self.HelpCommand = f'peahelp{CMD_INDEX}'
        self.LogCommand = f'pealog{CMD_INDEX}'
        self.CloneCommand = f'peaclone{CMD_INDEX}'
        self.CountCommand = f'peacount{CMD_INDEX}'
        self.WatchCommand = f'peawatch{CMD_INDEX}'
        self.ZipWatchCommand = f'peazipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'peaqb{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'peaqbunzip{CMD_INDEX}'
        self.QbZipMirrorCommand = f'peaqbzip{CMD_INDEX}'
        self.DeleteCommand = f'peadel{CMD_INDEX}'
        self.ShellCommand = f'peashell{CMD_INDEX}'
        self.ExecHelpCommand = f'peaexechelp{CMD_INDEX}'
        self.LeechSetCommand = f'pealeechset{CMD_INDEX}'
        self.SetThumbCommand = f'peasetthumb{CMD_INDEX}'
        self.LeechCommand = f'pealeech{CMD_INDEX}'
        self.UnzipLeechCommand = f'peaunzipleech{CMD_INDEX}'
        self.ZipLeechCommand = f'peazipleech{CMD_INDEX}'
        self.QbLeechCommand = f'peaqbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'peaqbunzipleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'peaqbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'pealeechwatch{CMD_INDEX}'
        self.LeechZipWatchCommand = f'pealeechzipwatch{CMD_INDEX}'
        self.RssListCommand = f'pearsslist{CMD_INDEX}'
        self.RssGetCommand = f'pearssget{CMD_INDEX}'
        self.RssSubCommand = f'pearsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'pearssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'pearssset{CMD_INDEX}'

BotCommands = _BotCommands()
